export const projects = [
  {
    title: 'Via Mario Shopping App',
    description:"This is basically a Full Stack E-commerce Web application which helps you to make online shopping for your choice goods. It connects buyers with sellers online.",
    image: '/images/mario-pic.png',
    tags: ['Node.js', 'Passport.js', 'ejs', 'MongoDB', 'Express'],
    source: 'https://github.com/AbaniwoM/viamario-shopping-app',
    visit: 'https://viamario-shopping-app.herokuapp.com/',
    id: 0,
  },
  {
    title: 'Budget Tracker Application',
    description:"An Application used to track your income and expense to enable you plan your budget",
    image: '/images/expense_tracker_app.png',
    tags: ['React.js', 'Material-ui'],
    source: 'https://github.com/AbaniwoM/budget_tracker_app',
    visit: 'https://my-income-expense-tracker-app.netlify.app/',
    id: 1,
  },
  {
    title: 'REST API React Project',
    description:"This is basically a project which involves consuming the endpoints from an available API. It displays loading time with conditional-rendering and manages the contents of the API with React.js.",
    image: '/images/form_plus.png',
    tags: ['React.js', 'css-grid', 'conditional-rendering', 'hooks-api-react'],
    source: 'https://github.com/AbaniwoM/formplus-task',
    visit: 'https://mike-abaniwos-form-plus-technical-task.netlify.app/',
    id: 2,
  },
  {
    title: 'Bible Quiz Application',
    description:"This is a Quiz application built for The SOUL Winner Evangelism platform online. It was built with React.js. Fully responsive.",
    image: '/images/soul-quiz.png',
    tags: ['React.js'],
    source: 'https://github.com/AbaniwoM/soulwinners-bible-quiz-app',
    visit: 'https://the-soulwinners-bible-quiz-app.netlify.app/',
    id: 3,
  },
  {
    title: 'My Pasteries Application',
    description:"Get your favourite  pasteries ready in time and make your order. This app was built with React.js.",
    image: '/images/pastery-img.png',
    tags: ['React.js'],
    source: 'https://github.com/AbaniwoM/Pastery-app',
    visit: 'https://my-pasteries.netlify.app/',
    id: 4,
  },
  {
    title: 'LoanVest',
    description:"This is basically a FinTech application which helps you to apply for loans and at the same time invest is any venture of your choice. It is very user friendly.",
    image: '/images/loanvest2.png',
    tags: ['React.js', 'Firebase'],
    source: 'https://github.com/AbaniwoM/loanvest',
    visit: 'https://loanvest.netlify.app/',
    id: 5,
  },
  {
    title: 'Material-ui/React-media-app',
    description:"This is a unique media app built with Material-ui and React.js. It covers the basic functionalities of material-ui.",
    image: '/images/react-material.png',
    tags: ['React.js', 'material-ui'],
    source: 'https://github.com/AbaniwoM/material-ui-react-media-app',
    visit: 'https://material-ui-react-media-app.netlify.app/',
    id: 6,
  },
  {
    title: 'VetConsult',
    description:"I worked with a team which built the VetConsult web application. It is basically a site that bridges the gap between the veterinary doctors and pet owners.",
    image: '/images/about-hero.jpeg',
    tags: ['HTML', 'CSS', 'SASS', 'JavaScript', 'Node.js'],
    source: 'https://github.com/AbaniwoM/vetconsult-fe-pjt-46/tree/dev',
    visit: 'https://vetconsultweb.netlify.app/',
    id: 7,
  } 
];

export const TimeLineData = [
  { year: 2019, text: 'Started my journey', },
  { year: 2020, text: 'Worked as a frontend developer at Truparse Nigeria Limited', },
  { year: 2021, text: 'Built my first personal website with HTML and CSS', },
  { year: 2021, text: 'Started working as a frontend intern with Zuri Team', },
  { year: 2021, text: 'Started and ended an HNG internship training with Hotels.ng', },
  { year: 2022, text: 'Built my First Full Stack E-commerce Web Application', },
];